version: '3'

services: 
  postgres:
    image: 'postgres:14.2'
    ports:
      - "5433:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  caddy:
    build:
      context: ./
      dockerfile: Caddy.dockerfile
    image: gokulsajeev/to-do:Caddy-latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - caddy_config:/config

  to-do:
    build:
      context: ./
      dockerfile: dockerfile
    image: gokulsajeev/to-do-app:latest
    restart: always
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1

volumes:
  # caddy_data:
  #   external: true
  caddy_config:
